### ISSUE TITLE
Make majorMentions produce implicitlyAbout annotations

### ISSUE THREAD

**Issue by davidlintonattheft** [Financial-Times/public-annotations-api#37]
Currently when editors tag with `about` then the public annotations API derives `implicitlyAbout` based on the concepts that are transitively broader than the tagged concept.

Guy would like tagged `majorMentions` to have the same effect.

Example: 1a342680-0724-11e8-9650-9c0ad2d7c5b5 is `about` `Glencore` and `majorMentions` `Mining` among other things

`Glencore` has no `broader` so it does not get any `implicityAbout`
Guy would like the `Mining` to qualify as well so that it is `implicitlyAbout` topics like `Energy` and `Companes`

Doing this now will mean the transition to Tagme is more seamless, as the effect of republishing an article through Tagme will be to convert existing `majorMentions` to `about`. After this change this conversion will not affect the `implicitlyAbout` tags.

**Comment by david-smith-ft** [comment]
Closed as we no longer produce majorMentions
